services:
  postgres:
    image: postgres:16
    container_name: energyflow-postgres
    environment:
      POSTGRES_DB: energyflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - energyflow_postgres_data:/var/lib/postgresql/data

volumes:
  energyflow_postgres_data: